"""Add limit to ExpenseCategory

Revision ID: 6b0c8517d51e
Revises: b20ace133200
Create Date: 2024-08-08 18:56:24.355619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b0c8517d51e'
down_revision = 'b20ace133200'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('limit', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense_categories', schema=None) as batch_op:
        batch_op.drop_column('limit')

    # ### end Alembic commands ###
