"""Updated limit calculation

Revision ID: b7ae3eb987fb
Revises: 6b0c8517d51e
Create Date: 2024-08-09 10:43:45.463893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7ae3eb987fb'
down_revision = '6b0c8517d51e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense_categories', schema=None) as batch_op:
        batch_op.alter_column('limit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense_categories', schema=None) as batch_op:
        batch_op.alter_column('limit',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)

    # ### end Alembic commands ###
